// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db_sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DatabaseSchema struct {
	TableName   string      `json:"table_name"`
	TableScript pgtype.Text `json:"table_script"`
}
